# Generated by Django 4.2.6 on 2023-12-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
