# Generated by Django 4.2.6 on 2023-12-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_one', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
