# Generated by Django 4.2.6 on 2024-01-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level_one', '0006_qnaquestion_qnaanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='{% static/img-quiz/ %}')),
                ('img_question', models.CharField(max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level_one.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='ImgAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_answer', models.CharField(max_length=255)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level_one.imgmodel')),
            ],
        ),
    ]
