# Generated by Django 4.2.6 on 2024-01-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_one', '0007_imgmodel_imganswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgmodel',
            name='img',
            field=models.ImageField(upload_to='static/assets/img_quiz'),
        ),
    ]
