# Generated by Django 4.2.6 on 2024-01-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_one', '0008_alter_imgmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgmodel',
            name='img',
            field=models.ImageField(upload_to='img_quiz'),
        ),
    ]
