# Generated by Django 4.2.6 on 2024-01-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level_one', '0010_rename_imgmodel_imgquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imganswer',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_answer', to='level_one.imgquestion'),
        ),
    ]
