# Generated by Django 4.2.6 on 2024-01-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_one', '0011_alter_imganswer_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgquestion',
            name='img_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imgquestion',
            name='img_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imgquestion',
            name='img',
            field=models.ImageField(blank=True, height_field='img_height', null=True, upload_to='img_quiz', width_field='img_width'),
        ),
    ]
