# Generated by Django 4.2.6 on 2024-01-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_one', '0012_imgquestion_img_height_imgquestion_img_width_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='MCQChoice',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='MCQQuestion',
        ),
    ]
