# Generated by Django 4.2.6 on 2024-01-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_one', '0015_qnaquestion_img_qnaquestion_img_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgquestion',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='ImgAnswer',
        ),
        migrations.DeleteModel(
            name='ImgQuestion',
        ),
    ]
