# Generated by Django 4.2.6 on 2024-03-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_one', '0016_remove_imgquestion_quiz_delete_imganswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnaquestion',
            name='qna_question',
            field=models.TextField(),
        ),
    ]
