# Generated by Django 4.2.6 on 2024-01-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_two', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hexahue',
        ),
        migrations.DeleteModel(
            name='TaskDetail',
        ),
    ]
