# Generated by Django 4.2.6 on 2024-01-20 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_score_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_task_urls', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
