# Generated by Django 4.2.6 on 2024-01-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_visitedtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedtasks',
            name='visited_task_urls',
            field=models.BooleanField(default=False),
        ),
    ]
