# Generated by Django 4.2.6 on 2024-01-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_visitedtasks_visited_task_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitedtasks',
            old_name='visited_task_urls',
            new_name='visited_level1_task1',
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level1_task2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level1_task3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level1_task4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level1_task5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level1_task6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level2_task1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level2_task2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level2_task3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level2_task4',
            field=models.BooleanField(default=False),
        ),
    ]
