# Generated by Django 4.2.6 on 2024-02-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_visited_task_urls_visitedtasks_visited_level1_task1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitedtasks',
            name='visited_level1_task6',
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level3_clue1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level3_clue2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level3_clue3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level3_task4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level4_task1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level4_task2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level5_task1',
            field=models.BooleanField(default=False),
        ),
    ]
