# Generated by Django 4.2.6 on 2024-02-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_visitedtasks_visited_level1_task6_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitedtasks',
            old_name='visited_level3_task4',
            new_name='visited_level3_clue4',
        ),
    ]
