# Generated by Django 4.2.6 on 2024-03-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_visited_level5_task1_visitedtasks_visited_level5_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedtasks',
            name='visited_level3_task',
            field=models.BooleanField(default=False),
        ),
    ]
